### ISSUE TITLE
It should let the domain class constructor free.

### ISSUE THREAD

**Issue by docteurklein** [RayRutjes/domain-foundation#4]
Currently, the abstract class that every aggregate root seems to extend avoids the usage of the constructor.
That's clearly a consequence of a technical, internal cause.

**Comment by rayrutjes** [comment]
This is a deliberate choice I have made to enforce the use of explicit, factory methods like 'register' for a user, or 'start' for a project.

Can you think of any drawback if I keep it as is?

**Comment by rayrutjes** [comment]
I close those for now, feel free to discuss this in another issue if you want to argue this is a problem.
