### ISSUE TITLE
[Help request] Reduce the amount of factories - phpspec side effect ?

### ISSUE THREAD

**Issue by rayrutjes** [RayRutjes/domain-foundation#6]
Hi all,

As you have noticed, as of today the library is very decoupled. We have introduced a lot of factories so that we respect the SRP, but this also allows us to mock everything when testing with phpspec.

@ciaranmcnulty, you argued on twitter that you never had to implement factories because of phpspec. I would really appreciate if you could take a look at my tests and maybe highlight where we went wrong.

The problem being that my classes are very behavioural, without much getters/setters.

I would like to deliberately couple some classes to others, and avoid the corresponding factories. I am for example thinking of the EventContainer.
In phpspec, there is no way to mock a class instantiated in a method, which makes it impossible to test subjects which have deliberate couplings.

Take the EventSourcedAggregateRoot as an example: https://github.com/RayRutjes/domain-foundation/blob/master/src/Domain/AggregateRoot/EventSourcedAggregateRoot.php

What if we simply wanted to instantiate an EventContainer directly without passing through a factory?
How would you write your tests in that case as you can no more expect calls on the EventContainer, and that is exactly what would need to be tested.

I have read the great articles proposed in this issue: https://github.com/phpspec/prophecy/issues/184
Specially liked the 'don't mock everything' one. But I kind of feel this can not be applied to phpspec, because if you don't mock, you can't test, and everything breaks. By the way, I came to the conclusion that phpspec has a philosophy of "mock everything" so that you work in complete isolation.

Would also love to see some links pointing towards existing libs tackling this phpspec/factories problem.

I sincerely hope I am wrong about some of my assertions about phpspec, so that i can adapt my existing codebase/tests, and continue to use this awesome tool!

**Comment by rayrutjes** [comment]
We have migrated to PhpUnit, which offered more flexibility in our tests.
We have removed all factories.

**Comment by lucascourot** [comment]
Tell me if I'm wrong but for me, you can do the same things with PHPSpec & [expect plugin](https://github.com/BossaConsulting/phpspec2-expect) and PHPUnit.

**Comment by rayrutjes** [comment]
We have moved to phpunit for several reasons, one of them being the community.
I find phpspec and more specificaly prophecy to be a wonderful tool. However, phpunit being able to to solve all our issues without additional dependencies, we moved away from phpspec.
Phpunit is also far more supported in third party tools, which is nice.
Please note that this is not a phpunit vs phpspec debate, both tools addresses the same issues, and both are great. I personally have not tested the expect plugin of phpspec you mentioned.
